package fr.atlantique.imt.inf211.jobmngt.entity;
// Generated 28 févr. 2025, 21:16:57 by Hibernate Tools 5.6.15.Final


import com.fasterxml.jackson.annotation.*;
import jakarta.persistence.*;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Joboffer generated by hbm2java
 */
@Entity
@Table(name = "joboffer"
        , schema = "public"
)
@NamedQueries({
        @NamedQuery(name = "JobOffer.findAll", query = "SELECT j FROM JobOffer j"),
        @NamedQuery(name = "JobOffer.findById", query = "SELECT j FROM JobOffer j WHERE j.id = :id"),
        @NamedQuery(name = "JobOffer.findByTitle", query = "SELECT j FROM JobOffer j WHERE j.title = :title"),
        @NamedQuery(name = "JobOffer.findByTaskdescription", query = "SELECT j FROM JobOffer j WHERE j.taskdescription = :taskdescription"),
        @NamedQuery(name = "JobOffer.findByPublicationdate", query = "SELECT j FROM JobOffer j WHERE j.publicationdate = :publicationdate"),
        @NamedQuery(name = "JobOffer.findByCompany", query = "SELECT j FROM JobOffer j WHERE j.company = :company"),
        @NamedQuery(name = "JobOffer.findByFieldAndQualif", query = "SELECT j FROM JobOffer j Where :field MEMBER OF j.fields and j.qualificationlevel = :qualificationLevel")
})
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class JobOffer implements java.io.Serializable {


    private int id;
    private Company company;
    private QualificationLevel qualificationlevel;
    private String title;
    private String taskdescription;
    private Date publicationdate;
    private Set<ApplicationMessage> applicationMessages = new HashSet<ApplicationMessage>(0);
    private Set<Field> fields = new HashSet<Field>(0);
    private Set<OfferMessage> offerMessages = new HashSet<OfferMessage>(0);

    public JobOffer() {
    }


    public JobOffer(int id, String title, String taskdescription, Date publicationdate) {
        this.id = id;
        this.title = title;
        this.taskdescription = taskdescription;
        this.publicationdate = publicationdate;
    }

    public JobOffer(int id, Company company, QualificationLevel qualificationlevel, String title, String taskdescription, Date publicationdate, Set<ApplicationMessage> applicationMessages, Set<Field> fields, Set<OfferMessage> offerMessages) {
        this.id = id;
        this.company = company;
        this.qualificationlevel = qualificationlevel;
        this.title = title;
        this.taskdescription = taskdescription;
        this.publicationdate = publicationdate;
        this.applicationMessages = applicationMessages;
        this.fields = fields;
        this.offerMessages = offerMessages;
    }

    @Id
    @SequenceGenerator(name = "JOBOFFER_ID_GENERATOR", sequenceName = "JOBOFFER_ID_SEQ", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "JOBOFFER_ID_GENERATOR")


    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "publisher")
    @JsonManagedReference
    public Company getCompany() {
        return this.company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "qualification")
    @JsonManagedReference
    public QualificationLevel getQualificationlevel() {
        return this.qualificationlevel;
    }

    public void setQualificationlevel(QualificationLevel qualificationlevel) {
        this.qualificationlevel = qualificationlevel;
    }


    @Column(name = "title", nullable = false)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }


    @Column(name = "taskdescription", nullable = false)
    public String getTaskdescription() {
        return this.taskdescription;
    }

    public void setTaskdescription(String taskdescription) {
        this.taskdescription = taskdescription;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "publicationdate", nullable = false, length = 13)
    public Date getPublicationdate() {
        return this.publicationdate;
    }

    public void setPublicationdate(Date publicationdate) {
        this.publicationdate = publicationdate;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "offermessdest", schema = "public", joinColumns = {
            @JoinColumn(name = "iddestoffer", nullable = false, updatable = false)}, inverseJoinColumns = {
            @JoinColumn(name = "idmessapp", nullable = false, updatable = false)})
    @JsonManagedReference
    public Set<ApplicationMessage> getApplicationmessages() {
        return this.applicationMessages;
    }

    public void setApplicationmessages(Set<ApplicationMessage> applicationMessages) {
        this.applicationMessages = applicationMessages;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "offerfields", schema = "public", joinColumns = {
            @JoinColumn(name = "offerid", nullable = false, updatable = false)}, inverseJoinColumns = {
            @JoinColumn(name = "idfield", nullable = false, updatable = false)})
    @JsonManagedReference
    public Set<Field> getFields() {
        return this.fields;
    }

    public void setFields(Set<Field> fields) {
        this.fields = fields;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "joboffer")
    @JsonManagedReference
    public Set<OfferMessage> getOffermessages() {
        return this.offerMessages;
    }

    public void setOffermessages(Set<OfferMessage> offerMessages) {
        this.offerMessages = offerMessages;
    }

    public String toString() {
        return "JobOffer{" +
                "id=" + id +
                ", company=" + company +
                ", qualificationlevel=" + qualificationlevel +
                ", title='" + title + '\'' +
                ", taskdescription='" + taskdescription + '\'' +
                ", publicationdate=" + publicationdate +
                ", applicationMessages=" + applicationMessages +
                ", fields=" + fields +
                ", offerMessages=" + offerMessages +
                '}';
    }

}


