package fr.atlantique.imt.inf211.jobmngt.entity;
// Generated 28 févr. 2025, 21:16:57 by Hibernate Tools 5.6.15.Final


import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import jakarta.persistence.GenerationType;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.GeneratedValue;

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message"
        , schema = "public"
)
public class Message implements java.io.Serializable {


    private int id;
    private String message;
    private Date publicationdate;
    private ApplicationMessage applicationmessage;
    private OfferMessage offermessage;

    public Message() {
    }


    public Message(int id) {
        this.id = id;
    }

    public Message(int id, String message, Date publicationdate, ApplicationMessage applicationmessage, OfferMessage offermessage) {
        this.id = id;
        this.message = message;
        this.publicationdate = publicationdate;
        this.applicationmessage = applicationmessage;
        this.offermessage = offermessage;
    }

    @Id
    @SequenceGenerator(name = "MESSAGE_ID_GENERATOR", sequenceName = "MESSAGE_ID_SEQ", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "MESSAGE_ID_GENERATOR")


    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }


    @Column(name = "message")
    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "publicationdate", length = 13)
    public Date getPublicationdate() {
        return this.publicationdate;
    }

    public void setPublicationdate(Date publicationdate) {
        this.publicationdate = publicationdate;
    }

    @OneToOne(fetch = FetchType.LAZY, mappedBy = "message")
    public ApplicationMessage getApplicationmessage() {
        return this.applicationmessage;
    }

    public void setApplicationmessage(ApplicationMessage applicationmessage) {
        this.applicationmessage = applicationmessage;
    }

    @OneToOne(fetch = FetchType.LAZY, mappedBy = "message")
    public OfferMessage getOffermessage() {
        return this.offermessage;
    }

    public void setOffermessage(OfferMessage offermessage) {
        this.offermessage = offermessage;
    }


}


