package fr.atlantique.imt.inf211.jobmngt.entity;
// Generated 28 févr. 2025, 21:16:57 by Hibernate Tools 5.6.15.Final


import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import jakarta.persistence.*;

import java.util.HashSet;
import java.util.Set;

/**
 * Qualificationlevel generated by hbm2java
 */
@Entity
@Table(name = "qualificationlevel"
        , schema = "public"
)
@NamedQueries(
        {
                @NamedQuery(name = "QualificationLevel.findAll", query = "SELECT q FROM QualificationLevel q order by q.id ASC"),
                @NamedQuery(name = "QualificationLevel.findByLabel", query = "SELECT q FROM QualificationLevel q WHERE q.label = :label"),
                @NamedQuery(name = "QualificationLevel.countAll", query = "select count(*) from QualificationLevel q"),
                @NamedQuery(name = "QualificationLevel.findById", query = "SELECT q FROM QualificationLevel q WHERE q.id = :id")
        }
)
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class QualificationLevel implements java.io.Serializable {


    private int id;
    private String label;

    private Set<JobOffer> jobOffers = new HashSet<JobOffer>(0);

    private Set<Application> applications = new HashSet<Application>(0);

    public QualificationLevel() {
    }


    public QualificationLevel(int id, String label) {
        this.id = id;
        this.label = label;
    }

    public QualificationLevel(int id, String label, Set<JobOffer> jobOffers, Set<Application> applications) {
        this.id = id;
        this.label = label;
        this.jobOffers = jobOffers;
        this.applications = applications;
    }

    @Column(name = "label", nullable = false)
    public String getLabel() {
        return this.label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    @Id
    @SequenceGenerator(name = "QUALIFICATIONLEVEL_ID_GENERATOR", sequenceName = "QUALIFICATIONLEVEL_ID_SEQ", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "QUALIFICATIONLEVEL_ID_GENERATOR")


    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "qualificationlevel")
    public Set<JobOffer> getJoboffers() {
        return this.jobOffers;
    }

    public void setJoboffers(Set<JobOffer> jobOffers) {
        this.jobOffers = jobOffers;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "qualificationlevel")
    public Set<Application> getApplications() {
        return this.applications;
    }

    public void setApplications(Set<Application> applications) {
        this.applications = applications;
    }


}


